apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ai

images:
- name: mo991207/ts-ai
  newName: 637423620662.dkr.ecr.ap-northeast-2.amazonaws.com/ts-ai
  newTag: "81"

patches:
  - target:
      kind: Deployment
      name: ai-deployment
      namespace: default
    path: deployment-patch.yml
  - target:
      kind: Service
      name: ai-service
      namespace: default
    path: service-patch.yml