apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment 
spec:
  template:
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "125m"
