apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment 
spec:
  template:
    spec:
      containers:
<<<<<<< HEAD
      - name: frontend
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "125m"
=======
        - name: frontend
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "64Mi"
              cpu: "125m"
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
>>>>>>> 6768da1 (Chore: Frontend 헬스 체크 추가)
