apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-restore-scripts
data:
  restore-script.sh: |
    #!/bin/bash
    echo "Starting mongorestore..."
    mongorestore --db tasty-saving --collection recipe /data/backup/tasty-saving/recipe/recipe.bson
    echo "mongorestore completed."