apiVersion: v1
kind: Pod
metadata:
  name: debug
  labels:
    purpose: debug
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command:
        - sleep
        - "3600"
      stdin: true
      tty: true