apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          volumeMounts:
            - name: mongodb-pv
              mountPath: /data/db               # MongoDB 데이터 저장 경로
            - name: mongodb-backup-pv
              mountPath: /data/backup           # BSON 파일 백업 경로
            - name: init-scripts-volume
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - containerPort: 27017
      volumes:
        - name: mongodb-pv
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: mongodb-backup-pv
          persistentVolumeClaim:
            claimName: mongodb-backup-pvc
        - name: init-scripts-volume
          configMap:
            name: mongodb-restore-scripts