apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/Users/mochang-il/Documents/ktb/TSP/mongo-tasty-saving-data"  # 실제 데이터가 저장될 경로
    type: DirectoryOrCreate  # hostPathType을 DirectoryOrCreate로 설정
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual  # PVC의 storageClassName도 manual로 설정