apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ts-config-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-paramstore
    kind: SecretStore
  target:
    name: ts-config-secrets
    creationPolicy: Owner
  data:
    - secretKey: app-name
      remoteRef:
        key: /ts/config/APP_NAME
    - secretKey: datasource-url
      remoteRef:
        key: /ts/config/SPRING_DATASOURCE_URL
    - secretKey: datasource-username
      remoteRef:
        key: /ts/config/SPRING_DATASOURCE_USERNAME
    - secretKey: datasource-password
      remoteRef:
        key: /ts/config/SPRING_DATASOURCE_PASSWORD
    - secretKey: hibernate-format-sql
      remoteRef:
        key: /ts/config/HIBERNATE_FORMAT_SQL
    - secretKey: hibernate-generate-ddl
      remoteRef:
        key: /ts/config/HIBERNATE_GENERATE_DDL
    - secretKey: show-sql
      remoteRef:
        key: /ts/config/SHOW_SQL
    - secretKey: open-in-view
      remoteRef:
        key: /ts/config/OPEN_IN_VIEW
    - secretKey: hibernate-ddl-auto
      remoteRef:
        key: /ts/config/HIBERNATE_DDL_AUTO
    - secretKey: database
      remoteRef:
        key: /ts/config/DATABASE
    - secretKey: kakao-client-id
      remoteRef:
        key: /ts/config/KAKAO_CLIENT_ID
    - secretKey: kakao-client-secret
      remoteRef:
        key: /ts/config/KAKAO_CLIENT_SECRET
    - secretKey: kakao-redirect-uri
      remoteRef:
        key: /ts/config/local/KAKAO_REDIRECT_URI
    - secretKey: kakao-authorization-uri
      remoteRef:
        key: /ts/config/KAKAO_AUTHORIZATION_URI
    - secretKey: kakao-token-uri
      remoteRef:
        key: /ts/config/KAKAO_TOKEN_URI
    - secretKey: kakao-user-info-uri
      remoteRef:
        key: /ts/config/KAKAO_USER_INFO_URI
    - secretKey: kakao-user-name-attribute
      remoteRef:
        key: /ts/config/KAKAO_USER_NAME_ATTRIBUTE
    - secretKey: openai-api-key
      remoteRef:
        key: /ts/config/OPENAI_API_KEY
    - secretKey: redis-host
      remoteRef: 
        key: /ts/config/local/REDIS_HOST
    - secretKey: redis-port
      remoteRef:
        key: /ts/config/REDIS_PORT