apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-paramstore
  namespace: default
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        secretRef:
          accessKeyIDSecretRef: # accessKeyId deprecated
            name: aws-credentials
            key: aws_access_key_id
          secretAccessKeySecretRef: # secretAccessKey deprecated
            name: aws-credentials
            key: aws_secret_access_key