apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: tasty-savings-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasty-savings-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # 배포 중 사용할 수 없는 최대 파드 수
      maxSurge: 1 # 배포 중 추가 생성할 수 있는 최대 파드 수
  template:
    metadata:
      labels:
        app: tasty-savings-backend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: backend
        image: ssssuji/ts-back:new2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /api/healthcheck
            scheme: HTTP
            port: 8080
        livenessProbe:
          httpGet:
            path: /api/healthcheck
            scheme: HTTP
            port: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "local"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: ts-config-secrets
              key: datasource-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: ts-config-secrets
              key: datasource-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ts-config-secrets
              key: datasource-password
        - name: HIBERNATE_FORMAT_SQL
          valueFrom:
            secretKeyRef:
              name: ts-config-secrets
              key: hibernate-format-sql
        - name: HIBERNATE_GENERATE_DDL
          valueFrom:
            secretKeyRef:
              name: ts-config-secrets
              key: hibernate-generate-ddl
        - name: SHOW_SQL
          valueFrom:
            secretKeyRef:
              name: ts-config-secrets
              key: show-sql
        - name: KAKAO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ts-config-secrets
              key: kakao-client-id
        - name: KAKAO_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ts-config-secrets
              key: kakao-client-secret
        - name: KAKAO_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: ts-config-secrets
              key: kakao-redirect-uri
      imagePullSecrets:
      - name: ecr-registry-secret