apiVersion: v1
kind: Service
metadata:
  name: loki-stack-grafana-nodeport
  namespace: loki
  labels:
    app.kubernetes.io/instance: loki-stack
    app.kubernetes.io/name: grafana
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: loki-stack
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 32000  # NodePort 범위(30000~32767) 내의 포트를 지정