apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: loki-stack
    meta.helm.sh/release-namespace: loki
  creationTimestamp: "2024-12-09T08:05:27Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-19.7.2
    component: server
    heritage: Helm
    release: loki-stack
  name: loki-stack-prometheus-server
  namespace: loki
  resourceVersion: "5187540"
  uid: 399d5306-0beb-4a6b-aa29-af386527a354
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gp2-csi
  volumeMode: Filesystem
status:
  phase: Pending