apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: back-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/tasty-savings/ts-infra'
    targetRevision: feature/TS-202
    path: overlays/prod/backend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy: {}