apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/backend

images:
- name: ssssuji/ts-back
  newName: 637423620662.dkr.ecr.ap-northeast-2.amazonaws.com/ts-backend
  newTag: "110"

patches:
  - target:
      kind: Deployment
      name: backend-deployment
      namespace: default
    path: deployment-patch.yml
  - target:
      kind: Service
      name: backend-service
      namespace: default
    path: service-patch.yml