apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: tasty-savings-backend
spec:
  type: ClusterIP
  selector:
    app: tasty-savings-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
