apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: ts-ec2nodeclass
  namespace: karpenter
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-ts-eks"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ts-eks"
      availabilityZones: ["ap-northeast-2a", "ap-northeast-2b"]
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ts-eks"