apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ts-nodepool
  namespace: karpenter
spec:
  template:
    metadata:
      labels:
        nodegroup: karpenter # 노드에 추가할 레이블
        alpha.eksctl.io/nodegroup-name: ts-karpenter-ng
    spec:
      requirements:
        - key: "nodegroup"
          operator: In
          values: ["karpenter"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t2"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["small", "medium"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: ts-ec2nodeclass
      expireAfter: 720h
  limits:
    cpu: 4
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m