apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: ts-ec2nodeclass
  namespace: karpenter
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-ts-eks"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ts-eks"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ts-eks"
  amiSelectorTerms:
    - id: "ami-090a5c6f86b8b8c75"