apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
  labels:
    app: tasty-savings-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasty-savings-ai  # 파드를 선택할 레이블
  template:
    metadata:
      labels:
        app: tasty-savings-ai  # 파드의 레이블 (selector와 일치)
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: ai
        readinessProbe:
          httpGet:
            path: /ai/health-check # 헬스체크 경로
            port: 5555
          initialDelaySeconds: 20 # 컨테이너 시작 후 첫 체크까지 대기 시간
          periodSeconds: 10 # 헬스 체크 간격
          timeoutSeconds: 3 # 체크 타임 아웃 설정
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ts-config-secrets
              key: openai-api-key