apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app: tasty-savings-ai
spec:
  selector:
    app: tasty-savings-ai
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
  type: ClusterIP
