apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: tasty-savings-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasty-savings-frontend
  template:
    metadata:
      labels:
        app: tasty-savings-frontend
    spec:
      containers:
      - name: frontend
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: frontend-config
        configMap:
          name: frontend-config
