apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: tasty-savings-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasty-savings-frontend
  template:
    metadata:
      labels:
        app: tasty-savings-frontend
    spec:
      containers:
      - name: frontend
        image: mo991207/ts-front:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
