apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yml
  - alb/cluster-role-alb.yml
  - config/configmap-alb.yml
  - alb/cert-manager.yml
  - alb/ingress-controller-alb.yml
  - alb/ingress-class.yml
  - ingress/ingress-alb.yml
  - autoscaler/service-account.yml
  - autoscaler/cluster-autoscaler.yml

images:
- name: ssssuji/ts-back  # 기존 이미지 이름 -> base 리소스 , 기존 실행되던 이미지이름
  newName: 637423620662.dkr.ecr.ap-northeast-2.amazonaws.com/ts-backend  # 새로운 이미지 이름
  newTag: "90"
- name: ssssuji/ts-front
  newName: 637423620662.dkr.ecr.ap-northeast-2.amazonaws.com/ts-frontend
  newTag: "106"
- name: mo991207/ts-ai
  newName: 637423620662.dkr.ecr.ap-northeast-2.amazonaws.com/ts-ai
  newTag: "52"
helmCharts:
  - name: argo-cd
    releaseName: argocd
    namespace: argocd
    version: 5.29.1 # 원하는 ArgoCD Helm 차트 버전
    repo: https://argoproj.github.io/argo-helm
    valuesInline:
      server:
        service:
          type: ClusterIP  # 필요한 경우 NodePort나 LoadBalancer로 변경
          spec:
            clusterIP: None
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: nodegroup
                      operator: In
                      values:
                        - autoscaler
      controller:
        replicaCount: 1
      configs:
        cm:
          kustomize.buildOptions: "--enable-helm"
patches:
  - target:
      kind: Deployment
      name: backend-deployment
      namespace: default
    path: backend/deployment-patch.yml
  - target:
      kind: Deployment
      name: frontend-deployment
      namespace: default
    path: frontend/deployment-patch.yml
  - target:
      kind: Deployment
      name: ai-deployment
      namespace: default
    path: ai/deployment-patch.yml
  - target:
      kind: Service
      name: backend-service
      namespace: default
    path: backend/service-patch.yml
  - target:
      kind: Service
      name: frontend-service
      namespace: default
    path: frontend/service-patch.yml
  - target:
      kind: Service
      name: ai-service
      namespace: default
    path: ai/service-patch.yml
  - target:
      kind: ExternalSecret
      name: ts-config-secrets
      namespace: default
    path: config/external-secret-patch.yml
  - target:
      kind: SecretStore
      name: aws-paramstore
      namespace: default
    path: config/secret-store-patch.yml

  
