apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: tasty-savings-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 7  # 최근 7개의 Revision만 유지
  selector:
    matchLabels:
      app: tasty-savings-frontend  # 파드를 선택할 레이블
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tasty-savings-frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodegroup
                    operator: In
                    values:
                      - karpenter
      terminationGracePeriodSeconds: 30
      containers:
        - name: frontend
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
          env:
          - name: VITE_APP_KAKAO_KEY
            valueFrom:
              secretKeyRef:
                name: ts-config-secrets
                key: vite-app-kakao-key
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      
