apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: tasty-savings-frontend
spec:
  replicas: 2
  template:
    spec:
      nodeSelector:
        role: frontend
      containers:
        - name: frontend
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
          tolerations:
            - key: "role"
              value: "frontend"
              effect: "NoSchedule"
