apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
spec:
  project: default
  source:
    repoURL: 'https://github.com/tasty-savings/ts-infra'
    targetRevision: feature/TS-202
    path: overlays/prod/frontend
    kustomize:
      namePrefix: front-
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true