apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/frontend

images:
- name: ssssuji/ts-front
  newName: 637423620662.dkr.ecr.ap-northeast-2.amazonaws.com/ts-frontend
  newTag: "131"

patches:
  - target:
      kind: Deployment
      name: frontend-deployment
      namespace: default
    path: deployment-patch.yml
  - target:
      kind: Service
      name: frontend-service
      namespace: default

    path: service-patch.yml