apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/frontend/deployment.yml
  - ../../../base/frontend/service.yml

patchesStrategicMerge:
  - deployment-patch.yml
  - service-patch.yml
