apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: tasty-savings-frontend
spec:
  type: ClusterIP
  selector:
    app: tasty-savings-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

