apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    releaseName: external-secrets
    namespace: external-secrets
    version: 0.10.3 # 원하는 버전으로 설정
    repo: https://charts.external-secrets.io
    valuesInline:
      installCRDs: true  # CRD 설치 포함
      serviceMonitor:
        enabled: false  # Prometheus 서비스 모니터링 옵션 (필요 시 활성화)
    includeCRDs: true  # CRD 포함 여부 설정

resources:
  - namespace.yml
  # - config/ecr-secret.yaml
#   - config/ecr-token-refresh.yml
# #  - config/aws-secret.yml
  - config/secret-store.yml
  - config/external-secret.yml
  - backend/deployment.yml
  - backend/service.yml
  - frontend/deployment.yml
  - frontend/service.yml
  - ai/deployment.yml
  - ai/service.yml

  # #mongodb_statefulset 
  - db-statefulset/mongodb-headless-service.yml
  - db-statefulset/mongodb-statefulset.yml

# commonLabels:
#   app: tasty-savings

commonAnnotations:
  project: "tasty-savings"
