apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tasty-savings/ts-infra'
    targetRevision: feature/TS-202
    path: overlays/prod/parent-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tasty-savings/ts-infra'
    targetRevision: feature/TS-202
    path: overlays/prod/frontend
    kustomize:
      namePrefix: front-
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tasty-savings/ts-infra'
    targetRevision: feature/TS-202
    path: overlays/prod/backend
    kustomize:
      namePrefix: back-
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tasty-savings/ts-infra'
    targetRevision: feature/TS-202
    path: overlays/prod/ai
    kustomize:
      namePrefix: ai
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true